email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  from: jobscout.test123@gmail.com
  to: jobscouttest123@gmail.com
  use_tls: true

results_per_day: 15          # was 10 — allow a few more to get signal

filters:
  remote_only: false         # keep hybrid + onsite + remote
  exclude_keywords:
    - "assistant"
    - "engineer"
  recent_days: 7             # was 1 — expand to last week so you actually get roles

allowed_types:
  - full-time
  - part-time
  - contract
  - casual
  - temporary

allowed_countries:
  - AU
  - UK
  - NZ
  - IE

salary_floor:
  au_yearly_gross: 60000     # was 65000 — small relax to avoid filtering out mid-level roles
  uk_yearly_gross: 28000     # was 31000 — same logic
  au_day_rate: 400           # was 450
  uk_day_rate: 200           # was 250
