email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  from: jobscout.test123@gmail.com
  to: jobscouttest123@gmail.com
  use_tls: true

results_per_day: 10

filters:
  remote_only: false   # include onsite + hybrid + remote
  exclude_keywords: 
    - "assistant"
    - "engineer"
  recent_days: 1       # only include jobs posted within last week

allowed_types:
  - full-time
  - part-time
  - contract
  - casual
  - temporary

allowed_countries:
  - AU
  - UK
  - NZ
  - IE

salary_floor:
  au_yearly_gross: 65000
  uk_yearly_gross: 31000
  au_day_rate: 450
  uk_day_rate: 250
