# ===============================
# JobScoutAI main configuration
# ===============================

# Email settings (auth comes from GitHub Secrets GMAIL_USER / GMAIL_PASS)
email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  from: jobscout.test123@gmail.com
  to: jobscouttest123@gmail.com
  use_tls: true

# How many jobs to include in the email
results_per_day: 10

# Filters
filters:
  remote_only: false

# These must be TOP-LEVEL (used by filters.py)
allowed_types:
  - full-time
  - part-time
  - contract
  - casual
  - temporary

allowed_countries:
  - AU
  - UK

# Salary floors (optional)
salary_floor:
  au_yearly_gross: 65000
  uk_yearly_gross: 31000
  au_day_rate: 450
  uk_day_rate: 250
