# ===============================
# JobScoutAI main configuration
# ===============================

# Email settings (auth via secrets GMAIL_USER / GMAIL_PASS)
email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  from: jobscout.test123@gmail.com
  to: jobscouttest123@gmail.com
  use_tls: true

# How many jobs to include in the daily digest
results_per_day: 10

# Global allowances (optional; code will handle missing)
allowed_types: ["full-time", "part-time", "contract", "casual"]
allowed_countries: ["AU", "UK"]

filters:
  remote_only: false      # include onsite + hybrid + remote
  recent_days: 7          # only jobs posted within last 7 days

# Salary floors (optional)
salary_floor:
  au_yearly_gross: 65000
  uk_yearly_gross: 31000
  au_day_rate: 450
  uk_day_rate: 250
