# --- who we send from/to & how to connect (uses your GMAIL_USER/GMAIL_PASS secrets for auth)
email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  from: jobscout.test123@gmail.com     # sender address to show in the email
  to: jobscouttest123@gmail.com        # where the digest is delivered
  use_tls: true

testing: false  # set true if you later switch to a sandbox

email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  username: ${GMAIL_USER}
  password: ${GMAIL_PASS}
  to: jobscouttest123@gmail.com

salary_floor:
  au_yearly_gross: 65000
  uk_yearly_gross: 31000
  au_day_rate: 450
  uk_day_rate: 250

allowed_types: ["full-time", "part-time", "contract", "casual"]
allowed_countries: ["AU", "UK"]
accept_remote: false
results_per_day: 10
