name: JobScout Daily

on:
  schedule:
    - cron: "0 22 * * *"  # 9am AEDT (UTC+11)
    - cron: "0 23 * * *"  # 9am AEST (UTC+10)
  workflow_dispatch: {}  # <-- this line MUST be here for the button

permissions:
  contents: read

jobs:
  jobscout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run JobScout
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          CONFIG_FILE: configs/felicity.yaml
        run: python daily_runner.py
