name: JobScout Daily

on:
  schedule:
    # 9:00 AM Melbourne
    # AEST (UTC+10): 23:00 UTC previous day
    # AEDT (UTC+11): 22:00 UTC previous day
    - cron: '0 23 * * *'   # use 22 for AEDT, 23 for AEST
  workflow_dispatch:

jobs:
  jobscout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run daily JobScout
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          ADZUNA_ID: ${{ secrets.ADZUNA_ID }}
          ADZUNA_KEY: ${{ secrets.ADZUNA_KEY }}
        run: python daily_runner.py

  test-scorer:
    # Only run the quick scorer test when triggered manually
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scorer smoke test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python test_scorer.py
