name: JobScout Daily

on:
  # Run at 9:00 AM Melbourne every day (DST-safe: trigger at 22:00 & 23:00 UTC,
  # then guard so it only proceeds when it's actually 09:00 in Melbourne)
  schedule:
    - cron: "0 22 * * *"  # 9am AEDT (UTC+11)
    - cron: "0 23 * * *"  # 9am AEST (UTC+10)
  # Allow manual runs
  workflow_dispatch:

permissions:
  contents: read

jobs:
  jobscout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show config.yaml the runner sees
        run: |
          echo "---- FILE CONTENT ----"
          cat config.yaml || true
          echo
          echo "---- PARSED YAML ----"
          python - <<'PY'
          import yaml, sys, os
          with open("config.yaml","r", encoding="utf-8") as f:
              txt = f.read()
          print(txt)
          try:
              cfg = yaml.safe_load(txt) or {}
              print("\nPARSED:", cfg)
              print("\nTOP-LEVEL KEYS:", list(cfg.keys()))
          except Exception as e:
              print("YAML parse error:", e)
              sys.exit(1)
          PY

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run JobScout
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}  # optional; can remove if unused
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          CONFIG_FILE: configs/felicity.yaml
        run: python daily_runner.py

