name: JobScout Daily

on:
  schedule:
    - cron: "0 22 * * *"
    - cron: "0 23 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  jobscout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show config.yaml contents
        run: |
          echo "---- FILE CONTENT ----"
          cat config.yaml || true
          echo "---- END FILE ----"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run JobScout
        run: python daily_runner.py
