name: JobScout Daily

on:
  schedule:
    - cron: "0 22 * * *"  # pick ONE of these; 9am Melbourne depending on DST
  workflow_dispatch:

concurrency:
  group: jobscout-daily
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  jobscout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Syntax check all Python
        run: |
          python -m py_compile daily_runner.py
          python -m py_compile core/*.py
          python -m py_compile collectors/*.py

      - name: Run JobScout
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          CONFIG_FILE: config.yaml
        run: python daily_runner.py
